# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  packageVersion: '1.0.0'

steps:
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'Sonar.Hygiene'
    organization: 'tylerkendrick-github'
    scannerMode: 'MSBuild'
    projectKey: 'TylerKendrick_Hygiene'
    projectName: 'Hygiene'
- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    feedsToUse: 'select'
    packagesToPack: 'Hygiene/Hygiene.csproj'
    versioningScheme: 'byEnvVar'
    versionEnvVar: 'packageVersion'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
- task: SonarCloudAnalyze@1